name: CI - Debug

run-name: Debug - ${{ github.ref_name || github.ref}}

on:
  workflow_dispatch: {} # run workflow 버튼 생성
  push:
    branches:
      - week3

jobs:
  ci_debugger:
    runs-on: self-hosted

    steps:
      - name: Template
        run: |
          echo "Hello, world!" > hello.txt
          dpkg --print-architecture >> hello.txt
          echo "This is a device running on ${{ runner.os }}"
          
      - name: Checkout
        uses: actions/checkout@v4

