name: CI - Debug

run-name: Debug - ${{ github.ref_name || github.ref}}

on:
  workflow_dispatch: {} # run workflow 버튼 생성
  push:
    branches:
      - week3

jobs:
  ci_debugger:
    runs-on:
      - ARM64

    steps:
      - name: Template
        run: |
          echo "Hello, world!"
          echo "This is a device running on ${{ runner.os }}"
          echo "This device's architecture is ${{ dpkg --print-architecture }}"

      - name: Checkout
        uses: actions/checkout@v4
